DROP TABLE IF EXISTS ARCS;
CREATE TABLE ARCS(
    ID INT PRIMARY KEY,
    JEUX VARCHAR(50),
    NOM VARCHAR(100),
    ATTAQUE INT,
    DURABILITE INT,
    PORTEE INT,
    MULTIFLECHES INT,
    VISEE VARCHAR(50),
    DISPONIBILITE VARCHAR(500)
   );

DROP TABLE IF EXISTS ARMES;
CREATE TABLE ARMES(
    ID INT PRIMARY KEY,
    JEUX VARCHAR(50),
    TYPEARME VARCHAR(50),
    NOM VARCHAR(100),
    ATTAQUEBASE INT,
    ATTAQUERANG1MAX INT,
    ATTAQUERANG2MAX INT,
    DURABILITEBASE INT,
    DURABILITERANG1MAX INT,
    DURABILITERANG2MAX INT,
    JETEFFET VARCHAR(500),
    JETBASE INT,
    JETBONUS INT,
    DISPONIBILITE VARCHAR(500)
   );

DROP TABLE IF EXISTS BOUCLIERS;
CREATE TABLE BOUCLIERS(
    ID INT PRIMARY KEY,
    JEUX VARCHAR(50),
    NOM VARCHAR(100),
    DURABILITE INT,
    ATTAQUE INT,
    DISPONIBILITE VARCHAR(500)
   );

DROP TABLE IF EXISTS INGREDIENTS;
CREATE TABLE INGREDIENTS(
    ID INT PRIMARY KEY,
    JEUX VARCHAR(50),
    NOM VARCHAR(100)
   );

DROP TABLE IF EXISTS VETEMENTS;
CREATE TABLE VETEMENTS(
    ID INT PRIMARY KEY,
    JEUX VARCHAR(50),
    SETVETEMENT VARCHAR(50),
    NOM VARCHAR(100),
    DEFMINI INT,
    DEFMAX INT,
    PARTIECORPS VARCHAR(500),
    LOCALISATION VARCHAR(500),
    EFFET VARCHAR(500),
    BONUSSET VARCHAR(500)
   );